import re
import unicodedata


JOURNAL_WHITELIST = (
    "Journal of Geophysical Research: Solid Earth",
    "Geophysical Research Letters",
    "Geophysical Journal International",
    "Bulletin of the Seismological Society of America",
    "Seismological Research Letters",
    "The Seismic Record",
    "Seismica",
    "Journal of Seismology",
    "Earthquake Science",
    "Pure and Applied Geophysics",
    "Earth, Planets and Space",
    "Earth and Planetary Physics",
    "Earth and Space Science",
    "Annals of Geophysics",
    "Acta Geophysica",
    "Studia Geophysica et Geodaetica",
    "Chinese Journal of Geophysics",
    "地球物理学报",
    "Applied Geophysics",
    "Journal of Geophysics and Engineering",
    "Geophysical Prospecting",
    "Geophysics",
    "The Leading Edge",
    "Interpretation",
    "Near Surface Geophysics",
    "Exploration Geophysics",
    "Journal of Applied Geophysics",
    "Earth and Planetary Science Letters",
    "Geochemistry, Geophysics, Geosystems",
    "Tectonics",
    "Tectonophysics",
    "Physics of the Earth and Planetary Interiors",
    "Solid Earth",
    "Lithosphere",
    "Geology",
    "GSA Bulletin",
    "Journal of Structural Geology",
    "Basin Research",
    "Terra Nova",
    "Geodynamics & Tectonophysics",
    "Geophysical and Astrophysical Fluid Dynamics",
    "Reviews of Geophysics",
    "Annual Review of Earth and Planetary Sciences",
    "Surveys in Geophysics",
    "Nature Geoscience",
    "Nature Communications",
    "Communications Earth & Environment",
    "Science Advances",
    "PNAS",
    "Scientific Reports",
    "Earth-Science Reviews",
    "Earth System Science Data",
    "The Innovation Geoscience",
    "National Science Review",
    "Science China Earth Sciences",
    "Earthquake Spectra",
    "Bulletin of Earthquake Engineering",
    "Earthquake Engineering & Structural Dynamics",
    "Soil Dynamics and Earthquake Engineering",
    "Earthquake Engineering and Engineering Vibration",
    "Journal of Earthquake Engineering",
    "Earthquake Research Advances",
    "Journal of Seismology and Earthquake Engineering",
    "Earthquake Engineering and Resilience",
    "Natural Hazards and Earth System Sciences",
    "Natural Hazards",
    "Landslides",
    "Engineering Geology",
    "Geomorphology",
    "Earth Surface Dynamics",
    "Earth Surface Processes and Landforms",
    "Journal of Volcanology and Geothermal Research",
    "Bulletin of Volcanology",
    "Volcanica",
    "Natural Hazards Review",
    "International Journal of Disaster Risk Reduction",
    "Geomatics, Natural Hazards and Risk",
    "Georisk: Assessment and Management of Risk for Engineered Systems and Geohazards",
    "Progress in Disaster Science",
    "Journal of Geodesy",
    "GPS Solutions",
    "Geodesy and Geodynamics",
    "Journal of Geodetic Science",
    "Remote Sensing of Environment",
    "Remote Sensing",
    "IEEE Transactions on Geoscience and Remote Sensing",
    "ISPRS Journal of Photogrammetry and Remote Sensing",
    "International Journal of Applied Earth Observation and Geoinformation",
    "Journal of Applied Remote Sensing",
    "Computers & Geosciences",
    "Geoscientific Model Development",
    "Environmental Modelling & Software",
    "SoftwareX",
    "Journal of Open Source Software",
    "Data in Brief",
    "Scientific Data",
    "Artificial Intelligence in Geosciences",
    "Machine Learning: Science and Technology",
    "International Geology Review",
    "Journal of Asian Earth Sciences",
    "Episodes",
    "Island Arc",
    "Geological Journal",
    "Geological Magazine",
    "Australian Journal of Earth Sciences",
    "Canadian Journal of Earth Sciences",
    "Russian Geology and Geophysics",
    "Geofizika",
    "Geologos",
    "Open Geosciences",
    "Frontiers in Earth Science",
    "PLOS ONE",
    "Heliyon",
    "Results in Geophysical Sciences",
    "地震学报",
    "Acta Seismologica Sinica",
    "地震",
    "Earthquake",
    "地震研究",
    "Journal of Seismological Research",
    "地震工程与工程振动",
    "中国地震",
    "地震地质",
    "地球科学",
    "Earth Science",
    "中国科学: 地球科学",
    "中国科学：地球科学",
    "岩石学报",
    "地质学报",
    "高校地质学报",
    "大地测量与地球动力学",
    "地球信息科学学报",
)

JOURNAL_ALIASES = (
    "JGR Solid Earth",
    "Journal of Geophysical Research - Solid Earth",
    "GRL",
    "GJI",
    "BSSA",
    "SRL",
    "Earth Planets and Space",
    "Geochemistry Geophysics Geosystems",
    "G-Cubed",
    "Earth Planetary Science Letters",
    "EPSL",
    "Proceedings of the National Academy of Sciences",
    "Proceedings of the National Academy of Sciences of the United States of America",
    "Proceedings of the National Academy of Sciences of the USA",
    "Earth Science Reviews",
    "Earthquake Engineering and Structural Dynamics",
    "Natural Hazards Review ASCE",
    "International Journal of Applied Earth Observation and GeoInformation",
    "Computer and Geosciences",
    "Computers and Geosciences",
    "Environmental Modelling and Software",
    "Journal of Open Source Software JOSS",
    "Plos One",
    "Earthquake Research in China",
    "Seismology and Geology",
    "Acta Petrologica Sinica",
    "Acta Geologica Sinica",
    "Geological Journal of China Universities",
    "Journal of Geodesy and Geodynamics",
    "Journal of Geo-information Science",
)

_NON_NAME_CHAR_RE = re.compile(r"[^0-9a-z\u4e00-\u9fff]+")


def normalize_journal_name(name: object) -> str:
    text = unicodedata.normalize("NFKC", str(name or "")).casefold()
    text = text.replace("&", " and ")
    text = re.sub(r"\bthe\b", " ", text)
    text = _NON_NAME_CHAR_RE.sub(" ", text)
    return re.sub(r"\s+", " ", text).strip()


_ALLOWED_JOURNAL_KEYS = {
    normalize_journal_name(name)
    for name in (*JOURNAL_WHITELIST, *JOURNAL_ALIASES)
    if normalize_journal_name(name)
}

JOURNAL_WHITELIST_COUNT = len(JOURNAL_WHITELIST)


def is_allowed_journal(name: object) -> bool:
    return normalize_journal_name(name) in _ALLOWED_JOURNAL_KEYS
